# tex/Makefile
#
# commands
#   make           # build PDF and open it when possible
#   make pdf       # build PDF
#   make sp v=1    # build SP version and open it
#   make clean     # remove intermediate files

MAIN_DOC  ?= @FILENAME@
SUB_DOCS  ?=
REQUIRE_V ?= 0

MK_HOME ?= $(HOME)/local/share/mk
include $(MK_HOME)/tex/core.mk
